version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"
    groups:
      preact:
        patterns:
          - "preact*"
          - "@preact/*"
      build:
        patterns:
          - "vite*"
          - "esbuild*"
          - "@vitejs/*"
      test:
        patterns:
          - "vitest*"
          - "playwright*"
          - "@axe-core/*"
          - "jsdom*"
      lint:
        patterns:
          - "eslint*"
          - "prettier*"
          - "@typescript-eslint/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
